name: Build and Deploy
on:
  push:
    branches:
      - main
    paths:
      - "02-html/"
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Get talk title
        run: echo "TALK_TITLE=$(cat package.json | grep "name" | cut -d ':' -f 2 | cut -d '"' -f 2)" >> "$GITHUB_ENV"
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build build --base=/slides/${{env.talk_title}}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: slides/${{env.talk_title}}/dist
          target-folder: ${{env.talk_title}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
